language: php

php:
  - 5.4
  - 5.5

before_install:
  - sudo apt-get install libxslt-dev libxml2-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php -S 0.0.0.0:3000 -t public/

before_script:
  - composer install
  - bundle config build.nokogiri --use-system-libraries
  - bundle install --path vendor/bundle
  - php artisan migrate --package=cartalyst/sentry  
  - php artisan config:publish cartalyst/sentry  
  - php artisan migrate
  - php artisan db:seed

script:
  - bundle exec rspec spec
