language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo:
  false

before_script:
  # full clone @see http://qiita.com/azu/items/de4b5bc7b9c29480540e
  - git fetch --unshallow
  - git fetch origin master:refs/remotes/origin/master
  # setup application
  - sh ./setup_app.sh
  # exec phpunit
  - vendor/bin/behat --colors
  - vendor/bin/phpunit
  # exec codeSniffer
  - ./phpcs_check.sh
