language: php

php:
  - 5.4
  - 5.5

before_install:
  - wget http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-i686.tar.bz2
  - tar -xf phantomjs-1.7.0-linux-i686.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.7.0-linux-i686 /usr/local/phantomjs
  - apt-get install libxslt-dev libxml2-dev

before_script:
  - composer install
  - bundle config build.nokogiri --use-system-libraries
  - bundle install --path vendor/bundle

script:
  - bundle exec rspec spec
