language: php

php:
  - 5.4
  - 5.5

before_install:
  - sudo apt-get install libxslt-dev libxml2-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php -S 0.0.0.0:3000 -t public/ > /tmp/server.log 2>&1 &

before_script:
  - composer install
  - php artisan migrate --force
  - php artisan db:seed --force
  - php artisan vendor:publish --provider="Owl\Providers\TwitterBootstrapServiceProvider"
  - bundle config build.nokogiri --use-system-libraries
  - bundle install --path vendor/bundle

script:
  - bundle exec rspec spec
